[package]
name = "bitonic-sorter"
version = "0.1.0"
authors = ["turkeyzawa <p.vuml.jublard@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.6.5"
rand_pcg = "0.1.2"
rayon = "1.0.3"
num_cpus = "1.10.0"
